### ISSUE TITLE
GUAC Landing White *Invisible* Text

### ISSUE THREAD

**Issue by 0xCardinal** [guacsec/guac-landing#61]
![image](https://github.com/user-attachments/assets/93afd680-396f-45c3-bcb0-22bfcfd93982)
The text in the cards are white in color, hence invisible.

**Comment by funnelfiasco** [comment]
It looks like the issue is that the style isn't getting set properly. This was probably introduced — or at least uncovered — in 2cb1557. The text color in the `card-text` style is [only set on paragraph elements](https://github.com/guacsec/guac-landing/blob/main/themes/hugo-fresh/assets/fresh/partials/_cards.scss#L28), but the way those boxes are built, they don't have paragraph elements inside the list.

I think the right answer is probably to wrap the `{{ .text }}` with `<p>` and `</p>` in [/themes/hugo-fresh/layouts/partials/section1.html](https://github.com/guacsec/guac-landing/blob/main/themes/hugo-fresh/layouts/partials/section1.html#L26). Another solution would be to remove the `p` specification on the color in `card-text` in `_cards.scss`.

**Comment by 0xCardinal** [comment]
Yes, there can be multiple solutions for this problem, and all of them will get the work done. 

In the #62 I have added a color to the `li` tag, which also gets the work done, so whenever a `li` tag is used we need not worry about it being invisible again.
